import type { Metadata } from "next";
import '@/styles/globals.css'
import { cn } from "@/lib/utils";
import LayoutProvider from "@/components/providers/LayoutProvider";
import RecoilProvider from "@/components/providers/RecoilProvider";
import { Montserrat } from 'next/font/google'


const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('flex flex-col min-h-dvh font-mont w-full', montserrat.variable)}>
        <RecoilProvider>
          <LayoutProvider>
            {children}
          </LayoutProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};